modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Wandering%20Trader%20May%20Leave"
logoFile="icon.png"

[[mods]]
modId="wanderingtradermayleave"
version="1.1"
displayName="Wandering Trader May Leave"
displayURL="https://serilum.com/mod/wandering-trader-may-leave"
authors="Rick South"
description='''Adds a button to the Wandering Trader's screen which makes it disappear without violence.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, Michael W. S., t128, Tyler Behl, XAgent   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.wanderingtradermayleave]]
    modId="collective"
    mandatory=true
    versionRange="[8.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wanderingtradermayleave]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.6]"
    ordering="NONE"
    side="BOTH"
